#!/usr/bin/env bash


# Since spring 2021, there is a weird additional battery with “rate information
# unavailable” being shown. We simply remove that entry first.
acpi \
    | sed -E '/.*rate information unavailable/d' \
    | sed -E 's/.*Charging,/C/' \
    | sed -E 's/.*Full,/F/' \
    | sed -E 's/.*Discharging,/D/' \
    | sed -E 's/.*Unknown,/U/' \
    | sed -E 's/([[:digit:]]+)%, (([[:digit:]]{2}):([[:digit:]]{2}):([[:digit:]]{2}))?.*$/\1 % (\3:\4 h)/' \
    | sed -E 's/([[:digit:]]+)%/\1 %/' \
    | paste --delimiters="#" --serial \
    | sed -E 's/#/ \/ /'
