#!/usr/bin/env bash


acpi \
    | sed -E 's/.*Charging,/C/;s/.*Full,/F/;s/.*Discharging,/D/;s/.*Unknown,/U/;s/([[:digit:]]+)%, (([[:digit:]]{2}):([[:digit:]]{2}):([[:digit:]]{2}))?.*$/\1 % (\3:\4 h)/;s/([[:digit:]]+)%/\1 %/' \
    | paste --delimiters="#" --serial \
    | sed -E 's/#/ \/ /'
