#!/usr/bin/env sh

s=$(xset q | grep --color -i -E 'caps|num')
caps=$(echo $s | sed -r 's/.*Caps Lock: *([^ ]*).*/\1/')
num=$(echo $s | sed -r 's/.*Num Lock: *([^ ]*).*/\1/')

if [[ $caps == "on" ]]; then
    printf "|  \${font Symbola:size=11}⇪\$font\${voffset -1}  "
fi

if [[ $num == "on" ]]; then
    printf "|  \${font Symbola:size=11}🔒\$font\${voffset -1}  "
fi

printf "\n"
