#!/usr/bin/env sh

string=$(nmcli con show --active |\
    awk 'NR != 1' |\
    cut --fields 1 --delimiter=' ' |\
    paste --delimiter='&' -s |\
    sed -r 's/&/ & /g')

if test -z "$string"; then
    printf down
else
    printf "%s" "$string"
fi

device_addresses() {
    device="$1"

    nmcli dev show "$device" |\
        grep -E 'IP4\.ADDRESS' |\
        sed -r 's/IP4\.ADDRESS\[.+\]: *([^ \/]+)\/.*$/\1/'
}

active_devices=$(nmcli con show --active |\
                     awk 'NR != 1' |\
                     awk '{ print $4 }' |\
                     paste --delimiter=' ' -s)

string=$( ( for d in $active_devices; do
               echo "$(device_addresses "$d")" "($d)"
           done ) |\
             sort -u |\
             paste --delimiter='/' -s |\
             sed -r 's/\// \/ /g')

if test -n "$string"; then
    printf '  $color2  %s' "$string"
fi

echo
