#!/usr/bin/env sh
# Post-linking hook for rcm.


secure () {
  local arg

  for arg; do
    if [ -d "$arg" ]; then
      chmod 700 "$arg"
    elif [ -f "$arg" ]; then
      chmod 600 "$arg"
    fi
  done
}


# fix permissions of files and folders
secure ~/.msmtprc


# create vim sessions folder if non-existant
# [[ -d ~/.vim/sessions ]] || mkdir ~/.vim/sessions


# create post-new hook for notmuch (haven't found a way to do this -.-)
[[ -d $HOME/Mail/.notmuch/hooks ]] || mkdir -p $HOME/Mail/.notmuch/hooks
cat > $HOME/Mail/.notmuch/hooks/post-new <<EOF
#!/usr/bin/env sh
afew --new --tag --verbose
EOF
