# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
# ZSH_THEME="af-magic-mine"
ZSH_THEME="time-separates-us"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# plugins=(zsh-autosuggestions history-substring-search git git-annex)
plugins=(history-substring-search git git-annex)

# history suggestions are yellow, currently
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=3"

unsetopt beep sharehistory
autoload zmv

source $ZSH/oh-my-zsh.sh
source $HOME/.zsh/z/z.sh

# exports
# --> .zshenv

# general command redefinitions
alias grep='grep --color'
alias feh='feh --theme=default'
alias nmcli='nmcli --ask'
alias irb='irb --simple-prompt'
alias ghc='ghc -outputdir /tmp'

# general aliases
alias s='sudo'
alias c='clear'
alias v='emacsclient -a emacs'
alias so='source ~/.zshrc'
alias here='nohup urxvt -uc > /dev/null &'

alias pxx='ps ax o %cpu,%mem,comm,pid,start k-%cpu,-%mem'
alias px='pxx | head -20'

# misc
alias sortc='LC_COLLATE=C sort'
alias linesifs="IFS=$'\n'"
alias normalifs="unset IFS"

alias imap='killall -9 offlineimap && sleep 1 && offlineimap'
alias reconky='killall conky; conky -c ~/.conkyrc'
alias bt='sudo bluetoothctl'
alias pg='pdfgrep --ignore-case --page-number'

alias hids='cat /sys/class/hidraw/hidraw*/device/uevent | grep NAME'
alias pair_it='sudo pairing_tool /dev/`ls -l /sys/class/hidraw/hidraw*/device/driver | awk -F/ '/receiver/{print $5}'`'

alias vboxmods='sudo modprobe vboxdrv && sudo modprobe vboxnetadp && sudo modprobe vboxnetflt && sudo modprobe vboxpci'

# source ordered stuff
source $HOME/.zsh/interface.zsh

source $HOME/.zsh/suffixes.zsh
source $HOME/.zsh/globals.zsh

source $HOME/.zsh/directories.zsh
source $HOME/.zsh/dropbox.zsh
source $HOME/.zsh/ssh.zsh
source $HOME/.zsh/xdg-mime.zsh
source $HOME/.zsh/git.zsh
source $HOME/.zsh/systemctl.zsh
source $HOME/.zsh/files.zsh
source $HOME/.zsh/sbt.zsh
source $HOME/.zsh/power.zsh

# not ordered
alias wifi="iwconfig | grep -i --color quality | sed -r 's/.*=([^ ]+).*=([^ ]+).*/\1 (\2 dBm)/'"
alias hl="hledger"
function stripBankData {
    cat $1 | cut -d ';' -f 2,5,6,9 | awk -v FS=';' '{ print $4 ";" $3 ";" $1 ";" $2 }'
}
alias adbAsRoot="if adb kill-server; then; sudo adb start-server; else; adb devices; fi"
alias checkBuch="ledger --strict --f $HOME/Buchhaltung/Gesamt.journal bal"
function sumRSS {
    sumExpr=$(ps -e --format rss,comm | grep --color -i -E $1 | awk '{ print $1 }' | paste --delimiter + -s)
    echo $(( ( $sumExpr ) / 1000 ))
}
